# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66e1d2d48efe96d79eaca648654c7936ca7859b9a8971bfe36167484b48ccec12c3f4fd18e1f4067501f400c9687f8f3a01bc20eb5b8e47c681b2defa3fb8e27

test:
  secret_key_base: 169b1693566effa22208ca53398eea004fb27ebfa67153af4f29783e04e1ee9d43fee9ac30a693df8b5b7908496460d59c4bac5b64a543b0bfdd3cea1340d1ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
